im = imread('12003.jpg');
noise_mean = 0;
noise_var = 0.0001;
PSF = fspecial('motion', 7, 45);
im1 = blur_img(im, PSF, noise_mean, noise_var);
estimate_nsr = 0;
estimate_nsr1 = noise_var/var(im1(:));
im2 = deconvwnr(im1, PSF, estimate_nsr1);
subplot(2,2,1);
imshow(rgb2gray(im));
title('Original Image');
subplot(2,2,2);
imshow(im1);
title('Blurred Image');
subplot(2,2,3);
imshow(im2);
title('Rstorartion Image');
subplot(2,2,4);
imshow(im2double(rgb2gray(im)) - im2);
title('Difference Image');
